LogEntry
"2023-06-02T12:33:45,281625999+00:00 - iot-server/run "
"2023-06-02T12:33:45,280941497+00:00 - rsyslog/run "
"2023-06-02T12:33:45,282373001+00:00 - nginx/run "
"2023-06-02T12:33:45,283285904+00:00 - gunicorn/run "
"2023-06-02T12:33:45,284966810+00:00 | gunicorn/run | "
"2023-06-02T12:33:45,286853816+00:00 | gunicorn/run | ###############################################"
"2023-06-02T12:33:45,290424327+00:00 | gunicorn/run | AzureML Container Runtime Information"
"2023-06-02T12:33:45,292112533+00:00 | gunicorn/run | ###############################################"
"2023-06-02T12:33:45,294454041+00:00 | gunicorn/run | "
"2023-06-02T12:33:45,296291547+00:00 | gunicorn/run | "
"2023-06-02T12:33:45,299079456+00:00 | gunicorn/run | AzureML image information: openmpi4.1.0-ubuntu20.04, Materializaton Build:20230412.v4"
"2023-06-02T12:33:45,300456860+00:00 | gunicorn/run | "
"2023-06-02T12:33:45,301988865+00:00 | gunicorn/run | "
"2023-06-02T12:33:45,303457570+00:00 | gunicorn/run | PATH environment variable: /azureml-envs/azureml_de9419c94950cc4138fbfe8c5ea6de5b/bin:/opt/miniconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
"2023-06-02T12:33:45,305077775+00:00 | gunicorn/run | PYTHONPATH environment variable: "
"2023-06-02T12:33:45,306697780+00:00 | gunicorn/run | "
"2023-06-02T12:33:45,308163885+00:00 | gunicorn/run | Pip Dependencies (before dynamic installation)"

"EdgeHubConnectionString and IOTEDGE_IOTHUBHOSTNAME are not set. Exiting..."
"2023-06-02T12:33:45,349412220+00:00 - iot-server/finish 1 0"
"2023-06-02T12:33:45,350938825+00:00 - Exit code 1 is normal. Not restarting iot-server."
"adal==1.2.7"
"argcomplete==2.1.2"
"attrs==23.1.0"
"azure-common==1.1.28"
"azure-core==1.26.4"
"azure-graphrbac==0.61.1"
"azure-identity==1.13.0"
"azure-mgmt-authorization==3.0.0"
"azure-mgmt-containerregistry==10.1.0"
"azure-mgmt-core==1.4.0"
"azure-mgmt-keyvault==10.2.2"
"azure-mgmt-resource==22.0.0"
"azure-mgmt-storage==21.0.0"
"azureml-core==1.51.0"
"azureml-dataprep==4.10.7"
"azureml-dataprep-native==38.0.0"
"azureml-dataprep-rslex==2.17.11"
"azureml-dataset-runtime==1.51.0"
"azureml-defaults==1.51.0"
"azureml-inference-server-http==0.8.4"
"backports.tempfile==1.0"
"backports.weakref==1.0.post1"
"bcrypt==4.0.1"
"blis==0.7.9"
"cachetools==5.3.1"
"catalogue==2.0.8"
"certifi==2023.5.7"
"cffi==1.15.1"
"charset-normalizer==3.1.0"
"click==8.1.3"
"cloudpickle==2.2.1"
"confection==0.0.4"
"contextlib2==21.6.0"
"cryptography==40.0.2"
"cymem==2.0.7"
"distro==1.8.0"
"docker==6.1.2"
"dotnetcore2==3.1.23"
"et-xmlfile==1.1.0"
"Flask==2.2.5"
"Flask-Cors==3.0.10"
"fusepy==3.0.1"
"google-api-core==2.11.0"
"google-auth==2.19.0"
"googleapis-common-protos==1.59.0"
"gunicorn==20.1.0"
"humanfriendly==10.0"
"idna==3.4"
"importlib-metadata==6.6.0"
"importlib-resources==5.12.0"
"inference-schema==1.5.1"
"isodate==0.6.1"
"itsdangerous==2.1.2"
"jeepney==0.8.0"
"Jinja2==3.1.2"
"jmespath==1.0.1"
"joblib==1.0.1"
"jsonpickle==3.0.1"
"jsonschema==4.17.3"
"knack==0.10.1"
"langcodes==3.3.0"
"MarkupSafe==2.1.2"
"msal==1.22.0"
"msal-extensions==1.0.0"
"msrest==0.7.1"
"msrestazure==0.6.4"
"murmurhash==1.0.9"
"ndg-httpsclient==0.5.1"
"numpy==1.19.5"
"oauthlib==3.2.2"
"opencensus==0.11.2"
"opencensus-context==0.1.3"
"opencensus-ext-azure==1.1.9"
"openpyxl==3.0.10"
"packaging==23.0"
"pandas==0.25.3"
"paramiko==3.2.0"
"pathspec==0.11.1"
"pathy==0.10.1"
"pkginfo==1.9.6"
"pkgutil_resolve_name==1.3.10"
"portalocker==2.7.0"
"preshed==3.0.8"
"protobuf==4.23.2"
"psutil==5.9.5"
"pyarrow==9.0.0"
"pyasn1==0.5.0"
"pyasn1-modules==0.3.0"
"pycparser==2.21"
"pydantic==1.9.2"
"Pygments==2.15.1"
"PyJWT==2.7.0"
"PyNaCl==1.5.0"
"pyOpenSSL==23.1.1"
"pyrsistent==0.19.3"
"PySocks==1.7.1"
"python-dateutil==2.8.2"
"pytz==2023.3"
"PyYAML==6.0"
"requests==2.31.0"
"requests-oauthlib==1.3.1"
"rsa==4.9"
"SecretStorage==3.3.3"
"six==1.16.0"
"smart-open==6.3.0"
"spacy==3.4.0"
"spacy-legacy==3.0.12"
"spacy-loggers==1.0.4"
"srsly==2.4.6"
"tabulate==0.9.0"
"thinc==8.1.10"
"tqdm==4.65.0"
"typer==0.4.2"
"typing_extensions==4.6.2"
"urllib3==1.26.16"
"wasabi==0.10.1"
"websocket-client==1.5.2"
"Werkzeug==2.3.4"
"wrapt==1.12.1"
"xlrd==2.0.1"
"zipp==3.15.0"

"2023-06-02T12:33:45,833807698+00:00 | gunicorn/run | "
"2023-06-02T12:33:45,835369603+00:00 | gunicorn/run | ###############################################"
"2023-06-02T12:33:45,836916808+00:00 | gunicorn/run | AzureML Inference Server"
"2023-06-02T12:33:45,838416013+00:00 | gunicorn/run | ###############################################"
"2023-06-02T12:33:45,839859318+00:00 | gunicorn/run | "
"2023-06-02T12:33:46,811160183+00:00 | gunicorn/run | Starting AzureML Inference Server HTTP."
"2023-06-02 12:33:46,976 I [11] azmlinfsrv - Loaded logging config from /azureml-envs/azureml_de9419c94950cc4138fbfe8c5ea6de5b/lib/python3.8/site-packages/azureml_inference_server_http/logging.json"
"2023-06-02 12:33:47,051 I [11] gunicorn.error - Starting gunicorn 20.1.0"
"2023-06-02 12:33:47,051 I [11] gunicorn.error - Listening at: http://0.0.0.0:31311 (11)"
"2023-06-02 12:33:47,051 I [11] gunicorn.error - Using worker: sync"
"2023-06-02 12:33:47,054 I [69] gunicorn.error - Booting worker with pid: 69"
"Valid Application Insights instrumentation key provided."
"/azureml-envs/azureml_de9419c94950cc4138fbfe8c5ea6de5b/lib/python3.8/site-packages/azureml_inference_server_http/server/config.py:51: FutureWarning: aliases are no longer used by BaseSettings to define which environment variables to read. Instead use the ""env"" field setting. See https://pydantic-docs.helpmanual.io/usage/settings/#environment-variable-names"

"Azure ML Inferencing HTTP server v0.8.4"
"  class AMLInferenceServerConfig(pydantic.BaseSettings):"


"Server Settings"
"---------------"
"Entry Script Name: /structure/azureml-app/main.py"
"Model Directory: /var/azureml-app/azureml-models"
"Config File: None"
"Worker Count: 1"
"Worker Timeout (seconds): 300"
"Server Port: 31311"
"Health Port: 31311"
"Application Insights Enabled: true"
"Application Insights Key: AppInsights key provided"
"Inferencing HTTP server version: azmlinfsrv/0.8.4"
"CORS for the specified origins: None"
"Create dedicated endpoint for health: None"


"Server Routes"
"---------------"
"Liveness Probe: GET   127.0.0.1:31311/"
"Score:          POST  127.0.0.1:31311/score"

"2023-06-02 12:33:47,341 I [69] azmlinfsrv - AML_FLASK_ONE_COMPATIBILITY is set. Patched Flask to ensure compatibility with Flask 1."
"Initializing logger"
"2023-06-02 12:33:47,343 I [69] azmlinfsrv - Starting up app insights client"
"WARNING:opencensus.ext.azure.common:DeprecationWarning: Explicitly using instrumentation key isdeprecated. Please use a connection string instead."
"WARNING:opencensus.ext.azure.common:DeprecationWarning: Explicitly using instrumentation key isdeprecated. Please use a connection string instead."
"WARNING:opencensus.ext.azure.common:DeprecationWarning: Explicitly using instrumentation key isdeprecated. Please use a connection string instead."
"2023-06-02 12:33:48,097 E [69] azmlinfsrv - Traceback (most recent call last):"
"  File ""/azureml-envs/azureml_de9419c94950cc4138fbfe8c5ea6de5b/lib/python3.8/site-packages/azureml_inference_server_http/server/user_script.py"", line 74, in load_script"
"    main_module_spec.loader.exec_module(user_module)"
"  File ""<frozen importlib._bootstrap_external>"", line 783, in exec_module"
"  File ""<frozen importlib._bootstrap>"", line 219, in _call_with_frames_removed"
"  File ""/structure/azureml-app/main.py"", line 12, in <module>"
"    driver_module_spec.loader.exec_module(driver_module)"
"  File ""<frozen importlib._bootstrap_external>"", line 783, in exec_module"
"  File ""<frozen importlib._bootstrap>"", line 219, in _call_with_frames_removed"
"  File ""/structure/azureml-app/Codebase/score.py"", line 9, in <module>"
"    import spacy"
"  File ""/azureml-envs/azureml_de9419c94950cc4138fbfe8c5ea6de5b/lib/python3.8/site-packages/spacy/__init__.py"", line 14, in <module>"
"    from . import pipeline  # noqa: F401"
"  File ""/azureml-envs/azureml_de9419c94950cc4138fbfe8c5ea6de5b/lib/python3.8/site-packages/spacy/pipeline/__init__.py"", line 1, in <module>"
"    from .attributeruler import AttributeRuler"
"  File ""/azureml-envs/azureml_de9419c94950cc4138fbfe8c5ea6de5b/lib/python3.8/site-packages/spacy/pipeline/attributeruler.py"", line 6, in <module>"
"    from .pipe import Pipe"
"  File ""spacy/pipeline/pipe.pyx"", line 1, in init spacy.pipeline.pipe"
"  File ""spacy/vocab.pyx"", line 1, in init spacy.vocab"
"  File ""/azureml-envs/azureml_de9419c94950cc4138fbfe8c5ea6de5b/lib/python3.8/site-packages/spacy/tokens/__init__.py"", line 1, in <module>"
"    from .doc import Doc"
"  File ""spacy/tokens/doc.pyx"", line 36, in init spacy.tokens.doc"
"  File ""/azureml-envs/azureml_de9419c94950cc4138fbfe8c5ea6de5b/lib/python3.8/site-packages/spacy/schemas.py"", line 222, in <module>"
"    class TokenPattern(BaseModel):"
"  File ""pydantic/main.py"", line 205, in pydantic.main.ModelMetaclass.__new__"
"  File ""pydantic/fields.py"", line 491, in pydantic.fields.ModelField.infer"
"  File ""pydantic/fields.py"", line 421, in pydantic.fields.ModelField.__init__"
"  File ""pydantic/fields.py"", line 537, in pydantic.fields.ModelField.prepare"
"  File ""pydantic/fields.py"", line 634, in pydantic.fields.ModelField._type_analysis"
"  File ""pydantic/fields.py"", line 641, in pydantic.fields.ModelField._type_analysis"
"  File ""/azureml-envs/azureml_de9419c94950cc4138fbfe8c5ea6de5b/lib/python3.8/typing.py"", line 771, in __subclasscheck__"
"    return issubclass(cls, self.__origin__)"
"TypeError: issubclass() arg 1 must be a class"

"The above exception was the direct cause of the following exception:"

"Traceback (most recent call last):"
"  File ""/azureml-envs/azureml_de9419c94950cc4138fbfe8c5ea6de5b/lib/python3.8/site-packages/azureml_inference_server_http/server/aml_blueprint.py"", line 88, in setup"
"    self.user_script.load_script(config.app_root)"
"  File ""/azureml-envs/azureml_de9419c94950cc4138fbfe8c5ea6de5b/lib/python3.8/site-packages/azureml_inference_server_http/server/user_script.py"", line 76, in load_script"
"    raise UserScriptImportException(ex) from ex"
"azureml_inference_server_http.server.user_script.UserScriptImportException: Failed to import user script because it raised an unhandled exception"

"2023-06-02 12:33:48,097 I [69] gunicorn.error - Worker exiting (pid: 69)"
"2023-06-02 12:33:48,195 I [11] gunicorn.error - Shutting down: Master"
"2023-06-02 12:33:48,195 I [11] gunicorn.error - Reason: Worker failed to boot."
"Valid Application Insights instrumentation key provided."

"Azure ML Inferencing HTTP server v0.8.4"


"Server Settings"
"---------------"
"Entry Script Name: /structure/azureml-app/main.py"
"Model Directory: /var/azureml-app/azureml-models"
"Config File: None"
"Worker Count: 1"
"Worker Timeout (seconds): 300"
"Server Port: 31311"
"Health Port: 31311"
"Application Insights Enabled: true"
"Application Insights Key: AppInsights key provided"
"Inferencing HTTP server version: azmlinfsrv/0.8.4"
"CORS for the specified origins: None"
"Create dedicated endpoint for health: None"


"Server Routes"
"---------------"
"Liveness Probe: GET   127.0.0.1:31311/"
"Score:          POST  127.0.0.1:31311/score"

"2023-06-02T12:33:48,228865703+00:00 - gunicorn/finish 3 0"
"2023-06-02T12:33:48,230369608+00:00 - Exit code 3 is not normal. Killing image."
